CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    application_id VARCHAR(40) UNIQUE,
    tu4f_id VARCHAR(255) UNIQUE NOT NULL,
    date_submitted DATETIME DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    university VARCHAR(255),
    department VARCHAR(255) NOT NULL,
    admission_year INT NOT NULL,
    passout_year INT NOT NULL,
    ug_duration VARCHAR(50),
    contact_no VARCHAR(50),
    email VARCHAR(255),
    applying_for VARCHAR(100),
    higher_education BOOLEAN DEFAULT true,
    entrance_exam_appeared BOOLEAN,
    entrance_exam_name VARCHAR(100),
    entrance_exam_score VARCHAR(100),
    country VARCHAR(100),
    institute_admitted VARCHAR(255),
    pg_duration VARCHAR(50),
    pg_course VARCHAR(255),
    drive_folder_url VARCHAR(1024),
    ai_score_extracted VARCHAR(100),
    ai_verification_status ENUM('unverified', 'verified', 'discrepancy_detected', 'manual_check_needed') DEFAULT 'unverified',
    ai_verification_notes TEXT,
    ai_verification_result JSON,
    ai_confidence DECIMAL(5,2),
    ai_issues JSON,
    status ENUM('submitted','under_review','correction_required','approved','rejected','pending','partial','completed','follow_up') DEFAULT 'submitted',
    review_status ENUM('unchecked','checked') DEFAULT 'unchecked',
    notes TEXT,
    correction_reason TEXT,
    correction_token_hash CHAR(64),
    correction_token_expires_at DATETIME,
    correction_requested_at DATETIME,
    correction_used_at DATETIME,
    approved_at DATETIME,
    rejected_at DATETIME,
    drive_folder_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_students_status (status),
    INDEX idx_students_passout_year (passout_year),
    INDEX idx_students_correction_token (correction_token_hash)
);

CREATE TABLE IF NOT EXISTS documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT,
    doc_type ENUM('score_card','hall_ticket','offer_letter','transcript','lor','sop','passport','visa','other'),
    original_name VARCHAR(255),
    file_name VARCHAR(255),
    file_path VARCHAR(1024),
    file_size INT,
    mime_type VARCHAR(100),
    ocr_text LONGTEXT,
    ocr_result JSON,
    ai_verification_result JSON,
    verification_status ENUM('unverified','pass','warning','mismatch','manual_review') DEFAULT 'unverified',
    admin_verification_status ENUM('pending','verified','rejected') DEFAULT 'pending',
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS alumni (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    branch VARCHAR(255),
    passout_year INT,
    pg_university VARCHAR(255),
    pg_course VARCHAR(255),
    pg_country VARCHAR(100),
    pg_city VARCHAR(100),
    current_company VARCHAR(255),
    designation VARCHAR(255),
    email VARCHAR(255),
    linkedin_url VARCHAR(1024),
    phone VARCHAR(50),
    willing_to_mentor BOOLEAN DEFAULT true,
    areas_of_help JSON,
    photo_url VARCHAR(1024),
    source_student_id INT UNIQUE,
    alumni_status ENUM('active','inactive') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
