INSERT INTO alumni (name, branch, passout_year, pg_university, pg_course, pg_country, pg_city, current_company, designation, email, linkedin_url, phone, willing_to_mentor, areas_of_help) VALUES
('Rahul Sharma', 'IT', 2021, 'Stanford University', 'MS Computer Science', 'USA', 'Stanford', 'Google', 'Software Engineer', 'rahul.sharma@example.com', 'https://linkedin.com/in/rahulsharma', '+1-555-0123', true, '["Resume Review", "Interview Prep"]'),
('Priya Patel', 'Computer', 2020, 'Technical University of Munich', 'MSc Data Engineering', 'Germany', 'Munich', 'BMW Group', 'Data Scientist', 'priya.patel@example.com', 'https://linkedin.com/in/priyapatel', '+49-151-12345678', true, '["University Selection", "SOP Review"]'),
('Amit Kumar', 'Electronics', 2019, 'University of Toronto', 'MEng Electrical', 'Canada', 'Toronto', 'AMD', 'Hardware Engineer', 'amit.kumar@example.com', 'https://linkedin.com/in/amitkumar', '+1-416-555-0198', true, '["Career Guidance"]'),
('Sneha Reddy', 'EXTC', 2022, 'Imperial College London', 'MSc Communications', 'UK', 'London', 'BT Group', 'Network Engineer', 'sneha.reddy@example.com', 'https://linkedin.com/in/snehareddy', '+44-7700-900123', true, '["Visa Guidance", "Accommodation"]'),
('Vikram Singh', 'Mechanical', 2018, 'University of Melbourne', 'Master of Engineering', 'Australia', 'Melbourne', 'BHP', 'Mechanical Engineer', 'vikram.singh@example.com', 'https://linkedin.com/in/vikramsingh', '+61-412-345-678', false, '[]'),
('Neha Gupta', 'Computer', 2023, 'Carnegie Mellon University', 'MS Artificial Intelligence', 'USA', 'Pittsburgh', 'Meta', 'AI Researcher', 'neha.gupta@example.com', 'https://linkedin.com/in/nehagupta', '+1-412-555-0145', true, '["Research Guidance", "SOP Review"]'),
('Rohan Desai', 'IT', 2021, 'RWTH Aachen University', 'MSc Software Systems Engineering', 'Germany', 'Aachen', 'SAP', 'Software Developer', 'rohan.desai@example.com', 'https://linkedin.com/in/rohandesai', '+49-160-98765432', true, '["German Language Tips", "Job Search"]'),
('Anjali Verma', 'Civil', 2019, 'University of British Columbia', 'MEng Civil', 'Canada', 'Vancouver', 'PCL Construction', 'Project Manager', 'anjali.verma@example.com', 'https://linkedin.com/in/anjaliverma', '+1-604-555-0176', true, '["Networking", "PR Process"]'),
('Karan Shah', 'Mechatronics', 2020, 'University of Cambridge', 'MPhil Engineering', 'UK', 'Cambridge', 'ARM', 'Systems Engineer', 'karan.shah@example.com', 'https://linkedin.com/in/karanshah', '+44-7911-123456', true, '["Scholarship Info", "Interview Prep"]'),
('Pooja Joshi', 'Computer', 2022, 'University of Sydney', 'Master of IT', 'Australia', 'Sydney', 'Atlassian', 'Backend Developer', 'pooja.joshi@example.com', 'https://linkedin.com/in/poojajoshi', '+61-491-570-156', true, '["Course Selection"]');
